# Generated by Django 5.1.6 on 2025-02-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='PDF',
            new_name='PDF_file',
        ),
    ]
