# Generated by Django 5.1.6 on 2025-02-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_pdf_pdfdocument_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='PDF_file',
            field=models.FileField(upload_to=''),
        ),
    ]
