# Generated by Django 5.2 on 2025-05-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latest_schedule',
            field=models.JSONField(default=dict),
        ),
    ]
